[package]
name = "chronopwn_c2"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
aes-gcm = "0.10.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"